### ISSUE TITLE
Folder Copying Won't Start - Returns Blank Screen

### ISSUE THREAD

**Issue by karynrose1784** [ericyd/gdrive-copy#15]
I just started using the app today and successfully used it twice this morning, including one folder that was very large (over 2000 total files). However, when I try to start a new folder now, once I click "copy folder," it goes to a blank screen and doesn't start the copy (I checked my Drive to see if the new folder had been created and it was working in the background). I also tried using "Resume" to see if a previous copy was actually still in progress, but when I click "Resume copying," the same thing happens with the blank screen 

![capture](https://cloud.githubusercontent.com/assets/26976610/24769041/d1fd6072-1ab9-11e7-9f50-c69326680416.PNG)

**Comment by GASPARDYP** [comment]
I am having the same issue, and my folder is not too large. Actually, i thought that could be the issue and tried with a smaller folder and the same happened

**Comment by ericyd** [comment]
I can reproduce, but this isn't an issue with the app.  Google must have changed something with their Google Apps Service, which I imagine will be fixed soon.  It appears that they changed the headers that allow the google.script service to be accessed.

![image](https://cloud.githubusercontent.com/assets/8379268/24777220/30b2da24-1ad9-11e7-93ed-10057a8fce9a.png)

This is causing the google.script service to not be found.

![image](https://cloud.githubusercontent.com/assets/8379268/24777003/50a8eb4e-1ad8-11e7-80e4-6931424a5736.png)

I don't have any control over this, but I'll leave the issue open until Google resolves it.

**Comment by karynrose1784** [comment]
Thanks for your quick response, Eric. Seems whatever it was has been resolved as I've been able to use the app just fine this morning.

And, thank you for creating &maintaining this - it's been a real lifesaver in managing my drive.

**Comment by GASPARDYP** [comment]
I´m still experiencing the issue

![image](https://cloud.githubusercontent.com/assets/26979416/24812088/981c669a-1b7d-11e7-84f2-dbaa92c75d44.png)
